                                            <div class="panel-heading">
												<div class="row">
													<div class="col-xs-3">
														<i class="fa fa-flask fa-5x"></i>
														<h3 ng-bind="drug.email"></h3>
													</div>
													<div class="col-xs-9 text-right">
														<div class="huge" ng-bind="drug.id"></div>
														<div ng-bind="drug.fullName"></div>										
														<div ng-bind="drug.barcode"></div>	
													</div>
												</div>
											</div>