											<div class="form-group">
												<input class="form-control " type="text" ng-model="last_drug.fullName" placeholder="Полное наименование">
											</div>
											<div class="form-group">
												<input class="form-control " type="text" ng-model="last_drug.officialName" placeholder="Оффициальное наименование">
											</div>
											<div class="form-group">
												<textarea class="form-control " type="text" ng-model="last_drug.description" placeholder="Описание"></textarea>
											</div>					
											<div class="form-group">
												<input class="form-control " type="text" ng-model="last_drug.barcode" placeholder="Штрихкод">
											</div>